### ISSUE TITLE
pycryptodome安装不了啊

### ISSUE THREAD

**Issue by liang1024** [yop-platform/yop-python-sdk#5]
python -m pip install pycryptodome
Collecting pycryptodome
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/88/7f/740b99ffb8173ba9d20eb890cc05187677df90219649645aca7e44eb8ff4/pycrypto
dome-3.10.1.tar.gz
Exception:
Traceback (most recent call last):
  File "F:\code\yb_demo\lib\site-packages\pip-9.0.1-py3.6.egg\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "F:\code\yb_demo\lib\site-packages\pip-9.0.1-py3.6.egg\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "F:\code\yb_demo\lib\site-packages\pip-9.0.1-py3.6.egg\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "F:\code\yb_demo\lib\site-packages\pip-9.0.1-py3.6.egg\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "F:\code\yb_demo\lib\site-packages\pip-9.0.1-py3.6.egg\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "F:\code\yb_demo\lib\site-packages\pip-9.0.1-py3.6.egg\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "F:\code\yb_demo\lib\site-packages\pip-9.0.1-py3.6.egg\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "F:\code\yb_demo\lib\site-packages\pip-9.0.1-py3.6.egg\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
AttributeError: 'str' object has no attribute 'decode'

**Comment by liang1024** [comment]
直接用cryptodomex吧，2都不维护了，直接兼容3就好了

**Comment by yop-developer** [comment]
已经接受该建议，感谢反馈
